### ISSUE TITLE
code length overflow

### ISSUE THREAD

**Issue by hustcc** [gera2ld/jsqrgen#3]
code length overflow. (2084>1728)

当data内容太长的时候，我用于将url地址转成二维码。

**Comment by gera2ld** [comment]
二维码可以容纳的内容是有限的，内容越多，二维码就越大，越大的二维码就越不容易扫出来，所以对于很长的URL建议先转成短网址，然后生成二维码。

**Comment by hustcc** [comment]
我看jquery.qrcode.js是可以做到的啊~

**Comment by gera2ld** [comment]
因为它的typeNumber支持到了40，而jsqrgen只支持到了10

**Comment by hustcc** [comment]
使用你的这个做了chrome插件，上线了，第一个chrome插件。https://github.com/aTool-org/chrome-qrcode
