### ISSUE TITLE
生成logo出错

### ISSUE THREAD

**Issue by sharp** [gera2ld/jsqrgen#4]
你好， 我按照在线demo， image logo取的是一个jquery对象

```
  const canvas = qrgen.canvas({
    data: "#{@subscribe_url}",
    size: 300,
    height: 400,
    foreground: '#F77171',
    logo: {
      image: $('#logoImg')
    } 
  });
  document.getElementById('qrcode').appendChild(canvas);
```

错误是:

TypeError: Argument 1 of CanvasRenderingContext2D.drawImage could not be converted to any of: HTMLImageElement, HTMLCanvasElement, HTMLVideoElement, ImageBitmap.

**Comment by gera2ld** [comment]
image不能是jquery对象，只能是Image或者Canvas元素，可以用`$('#logoImg')[0]`。
